.travis.yml
heliopy/data/helios.py
heliopy/data/helper.py
heliopy/data/test/data_test.py
setup.py

Helios merged data download

---

heliopy/conftest.py
heliopy/data/test/data_test.py

Add option not to run data tests

---

heliopy/data/cluster.py
heliopy/data/test/data_test.py

Add PEACE moment data import

---

heliopy/data/helios.py

Split up Helios distribution importing

---

heliopy/data/helios.py

Return distribution functions as multi-index dataframes

---

heliopy/data/helios.py

Add advection, and remove general distribution method

---

heliopy/data/helios.py

Add date checks for helios merged data import

---

heliopy/data/helios.py

- Use timefilter
- Add `verbose` option to `mag_ness`
- Only save to hdf file in `mag_ness` if `use_hdf` is `True`
- Clean up `trajectory`

Helios fixes

---

heliopy/data/helios.py

and add method to save to hdf file.

Only save helios data to hdf if config var set

---

heliopy/data/helios.py

- Add verbose modes
- Properly close files
- Read in |B| for four hertz data

Helios updates

---

heliopy/data/ace.py
heliopy/data/test/data_test.py

ACE swe_h0 data import

---

doc/source/index.rst
doc/source/pycdf.rst
pycdf/README.md

Add pycdf to docs

---

.gitignore
.travis.yml

Build docs on travis

---

heliopy/data/helios.py

Use same directory as FTP site for 4Hz data

---

heliopy/data/helios.py

Reverts heliopython/heliopy#218

Revert "Use same directory as FTP site for 4Hz data"

---

heliopy/data/helper.py

Fix backslashes in urls

---

appveyor.yml
heliopy/data/cluster.py
heliopy/data/test/data_test.py
pytest.ini

Add windows CI

---

heliopy/data/ace.py
heliopy/data/artemis.py
heliopy/data/cluster.py
heliopy/data/helios.py
heliopy/data/helper.py
heliopy/data/imp.py
heliopy/data/messenger.py
heliopy/data/mms.py
heliopy/data/test/data_test.py
heliopy/data/ulysses.py
heliopy/data/wind.py
heliopy/util/config.py

Return a configuration dictionary to allow bools

---

heliopy/data/helper.py

Overhaul daysplitinterval

---

doc/source/index.rst
doc/source/whatsnew.rst

Add what's new page

---

heliopy/data/ace.py
heliopy/data/artemis.py
heliopy/data/cassini.py
heliopy/data/cluster.py
heliopy/data/helios.py
heliopy/data/helper.py
heliopy/data/imp.py
heliopy/data/messenger.py
heliopy/data/mms.py
heliopy/data/ulysses.py
heliopy/data/wind.py

Hide a bunch of helper methods from documentation

---

doc/source/examples/data_inventory.rst
doc/source/examples/examples.rst
doc/source/whatsnew.rst
heliopy/data/helper.py
heliopy/data/test/data_test.py

Add method to print amount of data stored locally

---

doc/source/whatsnew.rst
heliopy/data/test/data_test.py
heliopy/data/wind.py

Add wind sfpd data import

---

doc/source/development/testing.rst
doc/source/installing.rst

Add docs on testing

---

.circleci/config.yml
.gitignore
doc-requirements.txt
doc/Makefile
doc/source/code_ref/data/ace.rst
doc/source/code_ref/data/artemis.rst
doc/source/code_ref/data/cassini.rst
doc/source/code_ref/data/cluster.rst
doc/source/code_ref/data/helios.rst
doc/source/code_ref/data/helper.rst
doc/source/code_ref/data/imp.rst
doc/source/code_ref/data/index.rst
doc/source/code_ref/data/messenger.rst
doc/source/code_ref/data/mms.rst
doc/source/code_ref/data/ulysses.rst
doc/source/code_ref/data/wind.rst
doc/source/code_ref/index.rst
doc/source/conf.py
heliopy/data/cluster.py
heliopy/data/helper.py

Convert data to using automodapi

---

doc/source/spice.rst
heliopy/spice.py

Update spice docs

---

CHANGES.rst
examples/spice_orbit.py
heliopy/spice.py
heliopy/test/test_spice.py

Modify spice to take a list of times

---

.circleci/config.yml
.travis.yml
appveyor.yml
doc/source/conf.py
heliopy/__init__.py
requirements/test.txt
setup.cfg

Update continuous integration

---

CHANGES.rst
heliopy/data/helios.py
heliopy/data/spice.py
heliopy/data/test/test_data.py
heliopy/spice.py

And adapt the spice machinery for multiple spice kernels

Add Helios spice kernels

---

heliopy/data/ace.py
heliopy/data/artemis.py
heliopy/data/cassini.py
heliopy/data/helios.py
heliopy/data/helper.py
heliopy/data/imp.py
heliopy/data/messenger.py
heliopy/data/ulysses.py
heliopy/data/wind.py
test.py

Allow helper.load to not raise error if data not present

---

heliopy/data/spice.py

Just a small typo and PEP8 fix.

Small typo fix

---

heliopy/data/sunspot.py
heliopy/data/test/test_data.py
requirements/base.txt

Added multiple functions to import data from different time-frames. 
To use, 
```
import heliopy.data.sunspot as sunspot
sunspot.daily()
sunspot.monthly()
sunspot.yearly()
```
Will add the test files ASAP!

Added sunspot data importing with different timeframes

---

heliopy/data/sunspot.py

Fixed a documentation link

---

heliopy/data/spice.py

Added JUNO Reconstructed and JUNO Predicted SPK kernel files.

Added JUNO Kernel

---

CHANGES.rst

Added SPICE kernels, and removed one entry, because config returns path as string.

Updated Changelog

---

heliopy/data/spice.py

Add list of available kernels to docs

---

heliopy/data/test/test_data.py

This will work with #395 
Will fix the issues added to that.

Some edits to test_data.py

---

CHANGES.rst
doc/source/conf.py
requirements/docs.txt

Add issue linking to changelog

---

heliopy/data/artemis.py
heliopy/data/imp.py

Just some of the ticked boxes in the issue #416

Fixed some minor issues

---

heliopy/data/imp.py

Fixed column name duplicity. I used IMP's [Readme](http://cdaweb.gsfc.nasa.gov/pub/data/imp/imp8/mag/15s_ascii_v3/00_IMP8_15s_data_docum.txt).

Fixed column name duplicity

---

setup.cfg

Add versionfile_build

---

doc/source/guide/installing.rst

Add docs for installing conda

---

heliopy/data/ace.py
heliopy/data/artemis.py
heliopy/data/imp.py
heliopy/data/test/test_data.py
heliopy/data/util.py
requirements/base.txt

As the title states! A display of how it looks right now.

Added units importing for mfi_h0

---

doc/source/guide/citing.rst
doc/source/guide/configuring.rst
doc/source/guide/index.rst
doc/source/guide/installing.rst

Add citing page

---

heliopy/data/util.py

Some more refactoring that should make the code more readable, and easier to re-organise in the future.

Add new _get_remote_version function

---

heliopy/data/cassini.py

Close cassini files properly

---

heliopy/data/cassini.py
heliopy/data/test/test_data.py

The README is here, https://pds-ppi.igpp.ucla.edu/ditdos/download?id=pds://PPI/CO-E_SW_J_S-MAG-4-SUMM-1MINAVG-V1.0/DOCUMENT/USER_GUIDE/CASSINI_MAG_USER_GUIDE-131008.PDF 
Rs is Saturn Model Radius, which is around 60,000 KM.

Added units for Cassini 1min

---

doc/source/coords.rst
doc/source/index.rst
heliopy/coordinates/frames.py
heliopy/coordinates/test/test_transformations.py
heliopy/coordinates/transformations.py
setup.py

First attempt at some coordinates.

Coordinates

---

heliopy/data/ace.py
heliopy/data/util.py
requirements/base.txt

Added keys for mfi_h0, and documentation for util's unit_attach

mfi_h0 returns more data, and documentation fixes

---

.circleci/config.yml
doc/heliopy_theme/static/copybutton.js
doc/source/conf.py
doc/source/coords.rst
doc/source/development/testing.rst
heliopy/coordinates/__init__.py
heliopy/coordinates/frames.py

And the beginning of some coordinate documentation

Add doc tests

---

heliopy/data/wind.py

Removed multiple indices from swe_h3

Removed multi-index wind.swe_h3

---

heliopy/data/helios.py
heliopy/data/test/test_data.py

Got the units from the [README ](http://cdaweb.gsfc.nasa.gov/pub/data/helios/helios1/merged/he1_40sec/00readme.txt)available!

Added units for helios.merged

---

heliopy/data/test/test_data.py

df.data.index[0] == df.index[0] 
I didn't know this!

Edited test_data.py a bit

---

heliopy/data/helios.py
heliopy/data/test/test_data.py

I'm a bit confused about the units, but I think they are nanoteslas. 
The [document ](http://apollo.ssl.berkeley.edu/pub/helios-data/E2_experiment/Data_Cologne_Nov2016_bestdata/helios_igm_doc.pdf)I got the info from is in German, and has a like, tons of missing pages.

Added units for helios mag4hz

---

heliopy/data/util.py

EDIT: Woops, something wrong
EDIT 2: Now, along with units, the warning also prints the column name

Changed warning message for debugging purpose

---

heliopy/data/util.py

Close files if they are still open

---

heliopy/data/imp.py

Dropped useless columns from imp.merged

---

heliopy/data/mms.py

Updated fpi_dis_moms

---

examples/plot_importing_data.py
heliopy/data/helios.py
heliopy/data/imp.py
heliopy/data/util.py

No useless warnings if the CDF unit was already assigned a unit manually. <-- This is for the code refactor. Rest is as the commit says!

A bunch of stuff related to units

---

heliopy/data/util.py

Just a small workaround for the issue : https://github.com/sunpy/sunpy/issues/2657

Workaround for Nonetype issue

---

CHANGES.rst
doc/source/conf.py
doc/source/data/index.rst
examples/plot_timeseries.py
examples/timeseries.py
heliopy/data/ace.py
heliopy/data/artemis.py
heliopy/data/cassini.py
heliopy/data/helios.py
heliopy/data/imp.py
heliopy/data/ulysses.py
heliopy/data/util.py
heliopy/data/wind.py

Units Documentation

---

.travis.yml
CHANGES.rst
setup.py

Only support > 3.6

---

doc/source/conf.py

Adding default thumbnail

---

heliopy/data/helper.py

Well, astropy.units had day and year as units so I thought we should add them as well.

Added some units

---

heliopy/data/imp.py
heliopy/data/messenger.py

Converted functions to util.process

---

heliopy/data/imp.py

Got the units from the CDAWeb!

Added units to mag15s

---

CHANGES.rst
heliopy/data/wind.py

Fixed a lost commit and reverted wind.py to old version.

Some fixes

---

heliopy/data/imp.py
heliopy/data/util.py

This PR is to take care of the new column nomenclature

Made some changes to CDF Extraction

---

heliopy/data/wind.py

Attempting to convert, but there seems to be some problem. The function isn't returning any data. I'm pretty sure it is a really stupid mistake somewhere but I can't seem to find it.

Converted threedp_ functions to util.process

---

heliopy/data/test/test_data.py

Add method to check data output

---

CHANGES.rst
doc/source/data/dscovr.rst
doc/source/data/index.rst
heliopy/data/dscovr.py
heliopy/data/test/test_data.py
heliopy/data/util.py

Added mag_h0 from DSCOVR

---

heliopy/data/util.py

Add _save_hdf method

---

heliopy/data/util.py
requirements/base.txt

Now manual units are assigned to the automatically generated column names

Made changes to cdf_units function

---

.readthedocs.yml

Hopefully should fix the doc build, which has been failing for a long time!

Specify 3.6 on readthedocs

---

heliopy/data/util.py

Needs to be refactored into minimal code later.

Added another condition to attach units

---

heliopy/data/cassini.py
heliopy/data/cluster.py
heliopy/data/imp.py
heliopy/data/messenger.py
heliopy/data/mms.py
heliopy/data/ulysses.py

Some return statements that needed to be changed.

Added missing documentation

---

heliopy/data/spice.py

Added missing Ulysses Kernel

---

heliopy/data/imp.py
heliopy/data/util.py

Also remove some old code in util.process

Fix index setting for data.imp.merged

---

heliopy/data/mms.py
heliopy/data/test/test_data.py

Add mms_available_files function

---

heliopy/data/spice.py

Add predicted bepi columbo spice kernel

---

.circleci/config.yml
heliopy/coordinates/frames.py
requirements/base.txt
requirements/docs.txt

Add custom transformation graph

---

heliopy/data/spice.py

STEREO files listed dynamically

---

heliopy/data/cdasrest.py
heliopy/data/mms.py
requirements/extras.txt

Swap to using tqdm for progress bar

---

heliopy/data/omni.py

Replace bad values in OMNI data

---

heliopy/data/mms.py
heliopy/data/test/test_mms.py

Change allowed_probes of mms.py

Backport #719 to 0.7.x

---

azure-pipelines.yml
heliopy/coordinates/frames.py
heliopy/data/ace.py
heliopy/data/artemis.py
heliopy/data/cassini.py
heliopy/data/cluster.py
heliopy/data/helios.py
heliopy/data/imp.py
heliopy/data/mms.py
heliopy/data/test/test_spice.py
heliopy/data/ulysses.py
heliopy/data/util.py
setup.py

Backport #712 to 0.7.x

---

changelog/719.bugfix.rst
changelog/726.bugfix.rst
changelog/README.rst
pyproject.toml

Backport #729 on 0.7.x

---

heliopy/data/helios.py
requirements/extras.txt

Added Feature:
logic for mag_4hz to look at the http site rather then ftp. 
Other changes:
Moved remote_base_url to higher level
New dependencies:
bs4 which is under extra requirements
Removed:
Logic for FTP

mag_4hz HTTP logic

---

doc/heliopy_theme/docsidebar.html
doc/heliopy_theme/footer.html
doc/heliopy_theme/layout.html
doc/heliopy_theme/navbar.html
doc/heliopy_theme/static/style.css
doc/heliopy_theme/theme.conf
doc/source/conf.py
requirements/docs.txt

This is going to involve just manually copying across files, not ideal but how it works for now...

Update website to more recent sunpy-sphinx-theme

---

.circleci/config.yml
requirements/docs.txt

Run towncrier during doc build

---

requirements/extras.txt

Un-pin cdflib version

---

changelog/810.bugfix.rst
heliopy/data/mms.py
heliopy/data/test/test_mms.py

Mms narrow interval

---

heliopy/models/__init__.py
heliopy/models/test/test_models.py

Allow a user supplied rotation rate

---

heliopy/data/cassini.py
heliopy/data/test/test_cassini.py

Convert cassini mag to v2 of dataset

---

CHANGES.rst
heliopy/data/cassini.py
heliopy/data/psp.py
heliopy/data/test/test_cassini.py

Cassini v2

---

heliopy/data/util.py
pytest.ini

This removes some horrible custom code, and uses built in `cdflib` datetime code to speed up the conversion of CDF files to DataFrames

Speedup cdf loading

---

changelog/856.bugfix.rst
changelog/858.bugfix.rst
heliopy/data/helios.py
heliopy/data/test/test_helios.py
heliopy/data/test/test_mms.py
heliopy/data/test/util.py
heliopy/data/util.py

- Skip helios tests if website down

0.10.1 backports

---

heliopy/data/helper.py
heliopy/data/omni.py
heliopy/data/test/test_omni.py

Add other OMNI data products

---

heliopy/data/util.py

Adds a new `_download_url` method to directly download a file to a certain path.

Improve data download code

---

heliopy/data/spice.py

Check status code of spice links

---

heliopy/data/spice.py
heliopy/data/test/test_spice.py

Fixes https://github.com/heliopython/heliopy/issues/937

Update solar orbiter kernel

---

changelog/938.feature.rst
examples/plot_spice_orbit.py
heliopy/spice/spice.py

xref https://github.com/heliopython/heliopy/issues/937

Automatically furnish spice kernels

---

heliopy/data/spice.py

Fixes https://github.com/heliopython/heliopy/issues/986

Update PSP SPICE kernels

---

heliopy/data/psp.py

Fixes https://github.com/heliopython/heliopy/pull/988

Fix PSP FIELDS downloading
